//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DCAntiVirus.rc
//
#define IDD_DCANTIVIRUS_DIALOG          102
#define IDR_MENU1                       130
#define IDI_SHIELD_FRAME                132
#define IDS_SHEET                       133
#define IDB_CLAM_AV                     138
#define IDD_SETTINGS                    139
#define IDD_DIALOG_SHED                 140
#define IDD_DIALOG_SCAN                 141
#define IDD_DIALOG_MEMORY_SCAN          142
#define IDD_DIALOG_SCHED_SCAN           143
#define IDD_DIALOG_LOG                  144
#define IDR_LIST_CONTEXT                145
#define IDD_DIALOG_ALERT                146
#define IDD_DIALOG1                     147
#define IDD_SCAN_DLG                    147
#define IDC_BUTTON_DEL                  1000
#define IDC_BUTTON_QUARANTINE           1001
#define IDC_SHEET_POSITION              1005
#define IDC_BUTTON1                     1006
#define IDC_STARTDATE_SHED              1006
#define IDC_BUTTON_UPDATE_DB            1006
#define IDC_BUTTON_ADD                  1006
#define IDC_BUTTON_SCAN                 1006
#define IDD_STOP                        1006
#define IDC_BUTTON_STOP_MEMORY          1006
#define IDC_BUTTON2                     1007
#define IDC_STARTTIME_SHED              1007
#define IDC_BUTTON_MANUAL_SCAN          1007
#define IDC_BUTTON_ABOUT_SPEC_SCAN      1007
#define IDC_BUTTON3                     1008
#define IDC_EDIT1                       1009
#define IDC_EDIT_MAIN_DB_VERSION        1009
#define IDC_EDIT_IDLE_TIME              1009
#define IDC_EDIT1_CUR                   1009
#define ID_EDIT_CURRENT_MEMORY          1009
#define IDD_EDIT_CUR_SC                 1009
#define IDC_EDIT_LOAD                   1010
#define IDC_BUTTON_MEMORYL_SCAN         1010
#define IDC_EDIT3                       1011
#define IDC_EDIT_MAIN_DB_TIME           1011
#define IDC_EDIT_QUAR                   1011
#define IDC_EDIT4                       1012
#define IDC_EDIT_MAIN_DB_SIG            1012
#define IDC_DAILY_SHED                  1012
#define IDC_EDIT2                       1013
#define IDC_EDIT_DAILY_DB_VERSION       1013
#define IDC_WEEKLY_SHED                 1013
#define IDC_EDIT_TYPES                  1013
#define IDC_EDIT_TYPES_TO_SCAN          1013
#define IDD_EDIT_TYPES_SC               1013
#define IDC_EDIT5                       1014
#define IDC_EDIT_DAILY_DB_TIME          1014
#define IDC_MONTHLY_SHED                1014
#define IDD_EDIT_TYPES_SETT             1014
#define IDC_EDIT6                       1015
#define IDC_EDIT_DAILY_DB_SIG           1015
#define IDC_EDIT7                       1016
#define IDC_EDIT8                       1019
#define IDC_LAST_FILE_EDIT              1019
#define IDC_EDIT9                       1020
#define IDC_BUTTON_CHANGE_SCHED_SCAN    1020
#define IDC_EDIT_VIRUS_NAME             1020
#define IDC_BUTTON4                     1021
#define IDC_BUTTON_CHANGE_UPD           1021
#define IDC_RADIO1                      1022
#define IDC_EDIT10                      1022
#define IDC_RADIO_DENNY                 1022
#define IDC_EDIT_SERVICE_STATUS         1022
#define IDC_RADIO2                      1023
#define IDC_EDIT11                      1023
#define IDC_RADIO_ASK                   1023
#define IDC_CHECK1                      1024
#define IDC_EDIT12                      1024
#define IDC_CHECK_DEEP_SCANN            1024
#define IDC_EDIT_FILES_COUNT            1024
#define IDC_CHECK_INTERNAL_DB           1024
#define IDD_USE_INTERNAL                1024
#define IDC_EDIT13                      1025
#define IDC_BUTTON_DELETE_UPD           1025
#define IDC_CHECK2                      1026
#define IDC_EDIT14                      1026
#define IDC_CHECK_OFFICE                1026
#define IDC_CHECK3                      1027
#define IDC_CHECK_ARCHIVE               1027
#define IDC_CHECK4                      1028
#define IDC_CHECK_PDF                   1028
#define IDC_CHECK_HTML                  1029
#define IDC_CHECK_ENABLE_SCAN           1030
#define IDC_CHECK_ENABLE_IDLE_SCAN      1031
#define IDC_BUTTON_DELETE_SCHED_SCAN    1032
#define IDC_STATIC_SCAN_SHED            1033
#define IDC_STATIC_UPD_SHED             1034
#define IDC_LIST_ITEMS                  1035
#define IDC_BUTTON_REMOVE               1036
#define IDD_USE_INTERNAL_SETT           1037
#define IDC_STATIC_SCAN                 1039
#define ID_ITEMS_STATIC                 1039
#define IDC_LIST_ITEMS_SCAN             1040
#define IDD_ITEMS_LIST_SC               1040
#define IDC_BUTTON_ADD_ADD              1041
#define IDC_BUTTON_REMOVE_SCAN          1042
#define IDC_PROGRESS1                   1043
#define ID_PROGRES_MEMORY               1043
#define IDD_PROGRES_SC                  1043
#define IDC_STATIC_CURRENT              1046
#define ID_STATIC_CURRENT_MEMORY        1046
#define IDD_STATIC_CURRENT_SC           1046
#define IDC_STATIC_PROGRES              1047
#define ID_STATIC_PROGRES_MEMORY        1047
#define IDD_STATIC_SCAN_PROGRES_SC      1047
#define IDC_STATIC_ACTION               1048
#define IDD_STATIC_CURR_ACTION_SC       1048
#define IDC_STATIC_TYPES                1049
#define IDC_STATIC_ACTION2              1050
#define IDC_STATIC_TYPES_SETT           1050
#define IDC_STATIC_MEMORY_SCAN          1051
#define IDC_CHECK_MEM_INT_DB            1052
#define IDC_LIST_INFECTED               1054
#define IDC_STATIC_INFO                 1055
#define IDC_BUTTON_QUAR                 1056
#define IDC_COMBO_PRIORITY              1057
#define ID_LALA1_LALA2                  32771
#define ID_LALA1_LALA3                  32772
#define ID_MENU_VIEWFULLLOG             32773
#define ID_MENU_SETTINGS                32774
#define ID_MENU_45                      32775
#define ID_MENU_ENABLEON                32776
#define ID_MENU_1                       32777
#define ID_MENU_DELETEFILE              32778
#define ID_MENU_QUARANTINEFILE          32779
#define IDD_TYPES_SC                    65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        148
#define _APS_NEXT_COMMAND_VALUE         32780
#define _APS_NEXT_CONTROL_VALUE         1058
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
